flux_repo := "ssh://git@github.com/GianniBuoni/lab.git"

# Bootstraps flux onto the current context
@_bootstrap deploy_key:
    echo "=== Bootstrapping flux to $CLUSTER_BRANCH ==="; \
    flux bootstrap git \
    --private-key-file={{deploy_key}} \
    --url={{flux_repo}} \
    --branch=main \
    --path="clusters/$CLUSTER_BRANCH" \
    --silent; \
# create a new k3d cluster for quick testing
_k3d:
    k3d cluster create $CLUSTER_BRANCH \
    --no-lb \
    --k3s-arg "--disable=traefik@server:*" \
    --image rancher/k3s:latest \
    --subnet 172.28.0.0/16
