---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-auth
  namespace: woodpecker
spec:
  encryptedData:
    values.yaml: AgAHAGnXT5L56yLrV9pXL1bfTaT5cFVBVwXRJD/5MPio8Acc3nf149E/0zbjbSMwZjpYWMtmC4BcNtvTipjeYMOk5fYif7w3nAKqfPltaD+Db2Rp3pJnw/pvoOOm79T8KhJsivnh4/YMDvFaLqz8QDOKEV4+p71gM6IWtVatGyfVfsp7SI9vr4ipMjRyuE3hnFz2Upvtef3bUfqx/io8NnBwST5oC46VYt5rryUXVciaBVmbwIKA+2tt2pgx+JmqAYGyW+X4mdRXFxeS0t++0KcMSQPuA+gzx5ivYjugwKDjFEfP3uv18TFWUo5S+RLn7JJzoCVj54qaxhBQkwM+SLK1FjyuJ5Y6kE1lAz8XIB8VsWiuKzeG4DZhBxEV0ZRYBNxly90XiWVWRJMHBpUlk5kZmcnnnGTC938VcuzOqSbysQnpAmYFPlePsLBqTIflgmwrKkWa8fc1zPZhtEeMNbeyvG3EbMGI3RpF+uXWj0t8oKvUefRWaY9sPsHeUaRdtX6PgdLa59WFlthfSzGZ3nErgytuyl1L9TSUVAeWIqP668Lh9Ys11kjj4NHWwgs+vCRbUgSqZcgoTqSvo4aweoNQtPOBlGJdkyJEUS0U4raH6zzcTSxLD1/66iSP2JM+qOyz7qV8FY2gHBMbvJHxuH/WdvIFw5PIW4/stqTwUIUls42w8VKG6iCslw2beZ6RMAPyoMRo7rvzg3i/OCdLxCkiIqT12mSa09QsRDI8GN8OF2KLZV6WPbMmhIpO55dlodXIj9kC8jkFLDgVU3ERhAaFa7UrKViS6JAuM5HbZDTWaMa73w4lIglh+RYutEXrgOcsPssRSDWrXjMSirLdWkivnL6HMcr8okk2Xgksm4d4RqHaJH4PlN2egi9wkKmvgS6Xl9vmBEaMn0R7vDPPQog8x5BZmjlufF06Qkg9BZ1brIvyH1mOO35gGCMebXni47q5vxqhI/vT1B0zQheFh3+XhX9ec27YyrkqYC0DOeTrfywda7SuN1lSiEIcwoo0mHRfDDPWh9j6sGw8lNa3lFPKsRFMGj6KxZJfKIiFFV0bOmuQInrF0tMkSNhisyzFB849GhplxfT1iFWey1cYlySbTOc7FtJBhEbLipgFp6mNJN+R6ktVlRZmpF0O35nBlUVEyNnJDRKuyajZJrOrAClcIGk/NUVuTA5DpmrDvhHql20vUCAQGQz1Imq7OR8=
  template:
    metadata:
      name: woodpecker-auth
      namespace: woodpecker
