---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-auth
  namespace: woodpecker
spec:
  encryptedData:
    values.yaml: AgADdyEaf0JqEYOvuQstRLhhhoyec5Nd/pXuUYuHKwo8eD8fm0axeo9FgEwU/Ry21mM1fRPJl/54vb/gWaKbK/Kve+FU7+bdgI2YQ0UYkJfZL6wByvy6H18fj9r6XT0MjrC69c6rT8CF+JEUHaQMFeun6Bf+0rK8FoD22p0DLf3VMVmVTQYH4D0BFVTKONTmkGEPTAInIeModLBdkV3c46frKCxal3jGSiSKkbrhTz13kDoHUrLhzdQJZ50hsuSC3Zl1VUdG8mi32z+KbALlrizA/nicG3nwHQABDZNQiJ1LUeLvPDhLgFb5oLlBPkCit2WEfZa551+YM68hrU+QbyybU/q3g8S9mok9W6plsROVQMK84OgKZWN6G34OGJc09BJHeCfFhviwbg8uTA8OhSuGtR2hqXSLxmtr+kguQxflqD4B0QC2vujT+QRb1tOCLrDaaL6yHOGsw16RigYGJ84eFMJUJ3qvaAtpgr7/7r2Acm1MAJMkLQ/vs5MEi9+cwRX2u0rzwtE7oUpUBkVagjRh+zwQxOND1y/QIwLOGUfRK/UjJ68+2Ypb23f95Gtj4OAfyrHD/Fy1qaAwHjivMFxKgfLocrzjuHjLXwdYYStKIxHIHsyzmXjgAoxJWV94xYAGgNsOPD6qBPGkUSYKJTlnH4oyJTEnUsF27BlZxjtNI+poQFzf/jetZWPHuVaXCyjWI20Z4y1vy2zEQZHmPNVcD7hNNL2yzvx73TA2BboaN5LFy0Wp3mt93YrhweNyphrZEjoJOjnTd/Q4RrvZS7bxGpOiI/jMm/uBgvrXH5HNKUcNxjfSlPnH3FcATjK8S9UKPnhlM0tmcdN4YOxoeUsTs5GsdXNqixu8TjHN4q4k6cTPs+CfaJvzrLtHwVC4gW70O84YAUOeZbaBatntyDhR8s+nkTo/OSK/hG0=
  template:
    metadata:
      name: woodpecker-auth
      namespace: woodpecker
