apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: woodpecker-values
  namespace: woodpecker
  files:
  - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: HelmRelease
    name: woodpecker
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: woodpecker-values
