agent:
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_CLASS: ceph-fs
    WOODPECKER_BACKEND_K8S_STORAGE_RWX: "true"
    WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 5G
server:
  env:
    WOODPECKER_ADMIN: ParmaGianni,admin
    WOODPECKER_HOST: https://woodpecker.jonsimeon.com
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: https://fj.jonsimeon.com
    WOODPECKER_PLUGINS_PRIVILEGED: woodpeckerci/plugin-docker-buildx
    WOODPECKER_DATABASE_DRIVER: postgres
    WOODPECKER_DATABASE_DATASOURCE:
      valueFrom:
        secretKeyRef:
          name: woodpecker-db-app
          key: uri
