apiVersion: v1
kind: ConfigMap
metadata:
  name: woodpecker-values
  namespace: woodpecker
data:
  values.yaml: |
    server:
      env:
        WOODPECKER_ADMIN: ParmaGianni,admin
        WOODPECKER_HOST: https://woodpecker.jonsimeon.com
        WOODPECKER_FORGEJO: "true"
        WOODPECKER_FORGEJO_URL: https://fj.jonsimeon.com
        WOODPECKER_PLUGINS_PRIVILEGED: woodpeckerci/plugin-docker-buildx
