k_base := justfile_directory() + "/kustomizations"

# Runs a build of given kustomization
@build kustomization:
    kubectl kustomize \
    {{k_base}}/{{kustomization}}/$CLUSTER_BRANCH
    echo ""
# Apply a kustomization for testing purposes
@apply kustomization:
    kubectl apply -k \
    {{k_base}}/{{kustomization}}/$CLUSTER_BRANCH; \
# Boostrap secrets onto the current context
@secrets:
    echo "=== Boostrapping secrets to $CLUSTER_BRANCH ==="
    kubectl -n kube-system create secret tls sealed-secrets-key --cert="$TLS_CRT_FILE" --key="$TLS_KEY_FILE"
    kubectl -n kube-system label secret sealed-secrets-key sealedsecrets.bitnami.com/sealed-secrets-key=active
# Suspends flux kustomization reconciliation for cleanup/maitenence
@suspend:
    kustomizations=("core" "infra" "config" "apps"); \
    echo "=== Suspending flux kustomizations ==="; \
    for k in "${kustomizations[@]}"; do \
        echo "Suspending $k."; \
        flux suspend ks $k; \
        echo ""; \
    done
