apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    kind: ConfigMap
    name: fj-server
    namespace: forgejo
  patch: |
    - op: replace
      path: /data/FORGEJO__SERVER__DOMAIN
      value: fj.ext.noodoodle.us
    - op: replace
      path: /data/FORGEJO__SERVER__ROOT_URL
      value: http://fj.ext.noodoodle.us
    - op: replace
      path: /data/FORGEJO__SERVER__SSH_DOMAIN
      value: fj-ssh.ext.noodoodle.us
