providers:
  kubernetesCRD:
    allowCrossNamespace: true
service:
  enabled: false

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
  nfs:
    expose:
      default: false
    port: 2049
    exposedPort: 2049

  ssh:
    expose:
      default: false
    port: 2222
    exposedPort: 2222

  pals:
    expose:
      default: false
    port: 8211
    exposedPort: 8211
    protocol: UDP

  web-ext:
    expose:
      default: false
    exposedPort: 80
    port: 7080
    http:
      redirections:
        entryPoint:
          to: websecure-ext

  websecure-ext:
    expose:
      default: false
    exposedPort: 443
    port: 7443
