apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: woodpecker-ingress
spec:
  entryPoints:
  - web-ext
  routes:
  - match: Host(`woodpecker.jonsimeon.com`)
    services:
    - name: woodpecker-server
      port: http
