apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: woodpecker-db
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: woodpecker
      owner: woodpecker
