agent:
  replicaCount: 3
  tolerations:
  - key: storage
    operator: Exists
server:
  env:
    WOODPECKER_ADMIN: test,admin
    WOODPECKER_HOST: http://woodpecker.ext.noodoodle.us
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: http://fj.ext.noodoodle.us
    WOODPECKER_PLUGINS_PRIVILEGED: woodpeckerci/plugin-docker-buildx
    WOODPECKER_DATABASE_DRIVER: postgres
    WOODPECKER_DATABASE_DATASOURCE:
      valueFrom:
        secretKeyRef:
          name: woodpecker-db-app
          key: uri
