apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/actions-runner-controller
- ../../../features/cert-manager
- ../../../features/cloudflared
- ../../../features/cloudnative-pg
- ../../../features/rook-ceph-operator
- ../../../features/tailscale
- ../../../features/traefik
- ../../../features/traefik-int
- ../../../features/traefik-ext
components:
- ../../../components/secrets-prod/cloudflared-auth
- ../../../components/secrets-prod/tailscale-oauth
- ../../../components/tailscale-values-prod
- ../../../components/traefik-values
