---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCSeluQEA6sIHZFehjqnlb7NP4gyUJFCu52H4fNmGsH8y+POOlDRFn8bURtW3yo11WJ+iS2xSMg7++XmgbCzQdtwDC5zB3W3jLVaeEQsanPDhjN0MiIm6ctZfiW5jTVB8j7OU0ImRZs7tx+ywXMJDYUB9KwTA0jnlF+tntyNqDGoTzLfdY8Hg71RZiXQmkYhL5KfO8LxCL+8QW8PIAO1GkH1ey7pNHYJYwW7xRP9as7HUhOplZmUB3eLDgXC4iiWTRGcoWvbbxUr8wWEZwtndJLcHyPtU4bkG7rrh73idtRg0eD5FHamtEvk2pjdzbOS7tv+H6ZWA2XCPIGQaubWcPq/JCinfmT82fMCiZ/PzQonSsQLR6kWlk6p1d8m4GagvdOi3HvgDFhU985gXZBTMW/q/wukP28jupO9cG3PiInzjFAwyqQ7whhfCL5dKh388Ry2WmoK2B33HR5uFlEdBSkTLBa3YbG789zyDN95vnX3V5Ev69IdMBPaU4sUk9gm5MxSlU3FmShn/uP73SpNnPbGurvG/op35P83CRWtDfT3Ts8g586s68Eb+R16TBu20iNydb6214m3P0iD+HSYuGF9W1pkt9YXGoIlkSez0VX0mG5o10AkwP6vvHhMH4xcOVC5WZFdC5OGDdp1vx+GACJp6WW41eB81seU9M6cjrQfspUcQWiw/rOkp8JKfskjQQFkjLaduEcO+SF59ZPzZmzDMJJ4ygR7gq3qewHnVOBx+9dU5T25bCXwQxxgiIS+B1Id6rY+d/vJAWmZ0f3Yh2TrGb7puXtzNy4tPgMtfNJvZ5S2f4K+rkskOADQ9849jogMeampxwS5sdjc/tRuAG9gx9RhMTQbeVNMDj0H7e8EportHoe/zhiTTclKrypOuLIh0WfUU1MyfbIGEYx/+JNqQfrEtZkjM6aJoXGu7IaBSTOLi1l5DTl
  template:
    metadata:
      name: cloudflared
      namespace: cloudflared
