apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- token.yaml
patches:
- target:
    kind: Deployment
    name: cloudflared
    namespace: cloudflared
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value:
        name: TUNNEL_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflared
            key: token
