---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA4MYsTfzEnXBcWOlHNpkp3j/trrqaixqeYdia2Ws9BLIPMYkQstgpw4JP8Nk5O8/9aQLJKAMT6P9XApHDFlHABa+1dvQHYnueQnZ3OnofJhApDblpLTtHUjONiejqBO9PC03/8x1iWlX50UNInRn5jNroFfeRLTCQ0v9EqLFkpXkIe8QWw8O4xwaA5Vme7U+HxXk9WtjsS1gniPAoHZVuzjDS4Zg0bX1YHRsJYL67gGP7u9D52yBAWpL0IJbcUQMCYmObWlkEf0/HkutZCLwT68hOKG8Wbx7bds7yrLnz9Ap7HYugRC+8/JgJa1N8ggXrHjCFjoMIOq3dvXfSmo4WfUzsk/5BPRN8GyHB+JgcIVUuSzStZhc7iae1J/mcvpSL1E2lMC4RYoYv3ZQHoW/ulicVW45GgdyYmh1b0Ugv+caDw8aHiwryROrmXQA8QqGX/SQ/G17cJIaptRe78Tk4c4BKPUl2ep8OgIxRnjzMTdshGfP3GcgYcDGXKtL+Nk5u2FNl7PNSAUllSNiAKDcEtKWPYvX5kPAoOyIxrpbR4FN0U3B8/gnDLh0MvSQT2uyv0BywLGWW/dBn0ZpaKN+KfDtFRRBhdMm9nWqyQ25A7pMaGPFY7uVroJUoTFdig+r2/03Vp+s5YoXqpYNVCe94j9wttyujAHNTQrsnwhaxxnMTTRRfZBP2WJsQphN9sVc427Vsm1BlcHaHBhVnyzb+t+uDVvczUg/TKpLN9zUJmxXS0krXaKnhXfTx09G0Gu4YBNIoYCWrZ0aSRQESH6yZPtl35wTZvloRlC8gaOmnqGZARNvzUb25cvCdCZG12FbwfWWWslAznxgeyrrgcSnh8hSJ6FxsXssLuszwgICmNPrjsE5Yi7AfLO/jdFUNWc4IYBrx3bUhEa5aEkTimJDkdGdMQEy1fwJgrHDelLrZ7HsRADpJfHrGP
  template:
    metadata:
      name: cloudflared
      namespace: cloudflared
