---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-auth
  namespace: woodpecker
spec:
  encryptedData:
    values.yaml: AgAmCg1hUQ13C4utFMjO9O9F1ljruUp9YKohiEgXMNdttHaqdPdbjnB4wfs7FhrwbhHSMGdjy/glOUlrVqu3EjJWJoRyXVJKJX/fgHwL+LtCZGobE1xNowSQ5BRaFtZeqrjpzk6sf89QqIrXJeJmxIDxLRmgTYnqzBu1H95QXnqbCw60H2Ouy1jIAj8ZJgQ8LRpHaVsukIX93q7n62t4qPycXdgxFNfMsm/64GlxDmVE3LCybAi/Cxhdpp+EudoAjDsuQgdAH0TtGO3iJGgOqcuyQr8KlX7hqDai96J79KHjKs485yz1JTJqpks0zIj2AXyxMW10chYOwcm8WlnyiKwE7z6byvK7JbY0o1Cd6ctRI9iD4X8mADj9z4eO+ugabp3FoAVgKjapkLqXW2n0H9Dm1zhT3/GEH3tOip+O1OgIVezUZcisV2GUqObxxb/y5oSms7zt7X+bfYBdr4rxQVKYNAv/9hfromr9Hxn9UHTOk9JHq3SlrwbydgMkvlTfBl8ehF2NYY3jRpXK0nrFK0AcigZ2Md+2tf7Gzx6Y2MMa4E2yxifEjws0P9h26aj1jjtv6W6kugm20di2lHGo6N3B/04MGHxGaQVeUi0NE1ifEIcHiAfmpHZ4dOy+4BbzarOU0UOqC/5v9r6jMCDfHFhU2afwA429CHYv+7xUCybbuoJ8bIhf+iZXwCLjDrm2MhgdFiMIKUUwTdVcLRkB+BjJj3pUa0T04LzM5MdMIHxxN1IDrYVEp9Pk43u4VQ3/BKbZFfV5Kdtudn59p0Y7/2YCCFWjk8imPLc4353kYCsBLvnUAinCwnLyaDaYQ3IuXUuXNzm4BLmyoKCcIj3QFdXtB0wnNEhVb2c2+ot5VS28y32GroYc1xB1CEAfHTgrmkmdJYGk9+3Re/dYJMCa2xmAxJsZesDdakFaQyA5T7GqnGRH6T4y8JefTK2GdlLdKhlLdDuRytwTeZJieC9QCEO106ji7NRL3p0qJiFIIrdK+z/0XxTwP7/uIONbS0GvCw/GgKUG0gH6Y2G1dkQJU3CWbLUORznVpDj2K+NodgvJMqrzz2sS/NUgbvpvkMIBwQ1dqXwMCN1w6A9ZjFKRcNuJQF0jtwYO8X+rz8ywxU4c9G+UGzXdPCYkf5/vynZCJk51EdjIMVZniLqFvzNryW3/WE8BtkS8TOvnEV40IF2SqiWeUCTCiKVKEhBLV9Q=
  template:
    metadata:
      name: woodpecker-auth
      namespace: woodpecker
