---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-auth
  namespace: woodpecker
spec:
  encryptedData:
    values.yaml: AgAcVKTruqaI9qEMBUT1MJlPRD1OySlSltf71A0bdMQuh1sLgIe/P5HMUVvsDhodC9RM3QTme51mCctja+EgeR9ohGF3YFD0Ez9dNLx/3oTj/xq+t8H43562UU80pVaf6WAxrQZ/sasb6bDo6VbeLOOGlOwSRrzYLd9usXA+6vIvTk7SZvaCpbtniaQTQRz1CR/6Aj8rH9JjQ/7bbAROOF6qb5glG3tnjFE06QbmwTK0F4z9VyeWZkG2ROBhiC5DcoVFbSrFUInUjcM6WTO0lwe/Rg9+EXZ8BvjzjVi5G6cHtmHgV0+N2tVLklG/OBlXxNFD9jxydPZ8w3b3EEd15ImDxon+rbtwJvICalQtv5PZQcD5KeMhc4iMrOMDisopixQhh6v1unRfW5U8ZexScuhTP9DUjDGlOrlr6/68pfyRlXbt7SuxHQ4uWYqboxWF4e+jIO5a1cW+J0C2x9pz4Zl1xK2Ga4CMIzNFjMPzwdEUcpBCEdhTS9HQEyY+98xq6Kk2+hiQUnvOewdGPatdD1nxKEVcXeW/0ULxPtPXxc8IoJj2S5btPPlz14k2QWtbc3gr7I+q7IpRebott8vkIhTan6Hu8y/ke+ftIgN4sxbXYIVJpzQt/Y/RB7IdopAulgARwaAepE3gSULIZUvY5DxFjZYVGszsWmED1TqegmhUh2o6AeppZl5sTGtYG8i3ozxOpEFx/KvUnQwSl+XSROnqUWPbFIkskgBZoyUjMGi2DL6DcEnOBsNs2/L9IUx+1Vr06mt4sHWAHvw0gRxoMrkcaTIV6useh73zOadOSXZ0c39PCD6LS0YpeyyqBKDlaHh27We81UX4QQwdXC5mBmrzmTX10svSust1GqY5Xb6XM9VR6K87FBKcikd7C4fS5B4GWTqtxJuzdaDRfkMl8VVLx81rck8bepfGFPFRIH+YAFc8IPl89/8xDT8JTqAIM2VL/GrlCw8vdJO5/1o3FaXwKgnSvPiX/g7E8cSGpdpMoVJ6FHNm+eYf5i33PRXDvSHmQ9bIDcF81IMnUeRginSP9KmTo0sKUUs9eokpCR6Am0ZlP8riP9SgCUVP7HOsnBo49+YDsBTfQ73XG2Rgp7oQu+Lo/3+ouPsRFt5udjiGy/6fW/yhFmgWFrSox9TaBi9KjZUI3mhq5gOJwlsp1w0sl98SE0j0BwqpcO0MgxhV3SH/+IIkGeSUncE3oT4=
  template:
    metadata:
      name: woodpecker-auth
      namespace: woodpecker
