---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-auth
  namespace: woodpecker
spec:
  encryptedData:
    values.yaml: AgAPTOdB9iI1Rq5hkSxrCyzgV8jgvnN5kiGsNAw4+Kha6yYe3q/LDN1fb591TNdZ0gIIW3oH4QGaY8Tt1hNjvZFTjPxxoDicbTWR5Nflc3N3Tc76PWyeLrJVeeaxw7sWI6C/o1nefA/2ZvuJWtBCOG38EP2W4yXbQnOo2i4aLoXWRH0RyZvBhRY6NbTTTwddy5RMRZzYpv61oXFfKNxqkPbACZiibPRZ0P3+vTUEDY3DoUw8sc/G9DnBpozSeweCDrWdJUxOFvpo3YuK3uBnTdi/tm4EgLCuKbnvgltaVQX3NLzuG9ZDLOSTaKeJoeJNvLTA7EJWeTmevP51fzHI4uusT8sexl1LPbJy2hOZXeZBilCwp5XoOgF14r1jql8bZGWhChBiy3Q6H6wn3XpRS5IxkiI6rcHiSUMyaE1HkTFHJYxcphtRHJ5+ASblzBuJ+4JzA9xEVu/iu2W5cNL8TTIwIIJHiQcxqAlptETqm1xZh8bYivtzdnDKfmkRLpoCvvKh3oC1bj1vpzk4h4Pjb0eZkPZSbGSbl/F4jAQ4izaoPBTUWNG8QuKiLMOds+mS7YZRcRdJrV2voPqhQwtPJr6zkwUVbGo8LzHxzC719OwJxmIsWIa21t2DV/N5YsZlbPw5AlD143C7logxBEeM/GjQmYxkrRDExqxgu12742MvLqKFA+RAQas7XnNp5nv+NUBGmOGZtfyi7rXkqQ+fWrP3KYi67d6Z+NOsI523laZV1uv03lq3lPTpviX7lOzN1ndmZ47+ghMrwV7g/zV3zsUwjhvVUSm6fMw1AFCGGau1sqa9Kc93a2n429N+VZqKI9r2yel2F+p5Mfj8UjktZ22CBjyR8KT+NnkWMSA0DoEWG16yusu5jGJFu/MDslinEv7ga4whegOJdZRwNlUH6dZE0EZntdDzs7nmTmA=
  template:
    metadata:
      name: woodpecker-auth
      namespace: woodpecker
